Activity model and migration created
alkemyTech/OT141-SERVER pull request #1
Opened 2022-02-21 22:24 UTC by fedapon

COMO usuario administrador
QUIERO gestionar las Actividades de la ONG
PARA poder informarlas en el sistema

Criterios de aceptación:
Las Actividades de la ONG podrán ser gestionadas desde el backoffice. Nombre de tabla: activities. Contendrá los campos name, image, content, deletedAt (utilizada para soft delete)

2022-02-22 20:06 UTC, maxxCeballos requested changes

2022-02-22 20:06 UTC, maxxCeballos commented on migrations/20220219033006-create-activity.js
> +      },
Revisar tipo de dato para guardar imagenes

2022-02-22 20:06 UTC, maxxCeballos commented on models/activity.js
> +    content: DataTypes.STRING,
mismo caso que en migrations, revisar los tipos de datos para image y content

2022-02-22 20:06 UTC, maxxCeballos commented on models/activity.js
> +module.exports = (sequelize, DataTypes) => {
Dejar una o dos lineas entre distintas estructuras para poder visualizar mejor de forma separada lo que se esta importando de la logica propia del modulo.

2022-02-22 22:56 UTC, fedapon commented on models/activity.js
> +module.exports = (sequelize, DataTypes) => {
Se agregó el espaciamiento para facilitar la lectura.

2022-02-22 22:57 UTC, fedapon commented on migrations/20220219033006-create-activity.js
> +      },
Tipo de datos se mantiene en STRING ya que se utilizará para almacenar una URL

2022-02-23 23:54 UTC, maxxCeballos approved these changes

2022-02-24 03:00 UTC, merged