OT141-43 | Create category
alkemyTech/OT141-SERVER pull request #17
Opened 2022-02-26 00:50 UTC by nathandelgado-dev

Add a news categories with administrator privileges.

2022-03-01 03:20 UTC, maxxCeballos requested changes

2022-03-01 03:20 UTC, maxxCeballos commented on controllers/categories.js
> +    }
esta validación se hace en un middleware. Está siendo implementado por Ema. Tarea OT141-27. Mas alla de esto, si no estuviera implementado, hay dos responsabilidades en la misma funcion, crear una categoria y validar roles. Esta ultima deberia ir en una función aparte.

2022-03-01 03:20 UTC, maxxCeballos commented on routes/categories.js
> +  verifyToken,
se importa verifyToken y no se utiliza.

2022-03-01 03:20 UTC, maxxCeballos commented on controllers/categories.js
> +      });
En lugar de hacer estas validaciones por separado se podria hacer algo mas limpio, por ejemplo:
{
  name: nameUpper,
  description: description ? description : "" ( o null)
  image: image ? image : "" (o null)
}

Pensemos que si este objeto fuera mas completo y tendria 10 o mas atributos seria bastante engorroso hacer las validaciones de esta manera.

2022-03-01 15:56 UTC, nathandelgado-dev commented on controllers/categories.js
> +    }
Vale, ya implemente el middleware de Ema. Gracias.

2022-03-01 15:58 UTC, nathandelgado-dev commented on routes/categories.js
> +  verifyToken,
Olvide quitarle el comentario en la ruta, ya lo corregí.

2022-03-04 01:50 UTC, maxxCeballos approved these changes

2022-03-04 22:08 UTC, merged