Ot141-41 | List categories
alkemyTech/OT141-SERVER pull request #18
Opened 2022-02-26 16:47 UTC by nathandelgado-dev

Feature for get all categories

2022-03-01 18:21 UTC, maxxCeballos requested changes

2022-03-01 18:21 UTC, maxxCeballos commented on middlewares/categories.js
> +};
esto está fuera del alcance del ticket, pertenece a la otra tarea, esta todo lo agregado en el ticket de crear categoria mas el listar categoria.

2022-03-01 18:21 UTC, maxxCeballos commented on helpers/validateInDB.js
> +};
esto está fuera del alcance del ticket, pertenece a la otra tarea, esta todo lo agregado en el ticket de crear categoria mas el listar categoria.

2022-03-01 18:21 UTC, maxxCeballos commented on controllers/categories.js
> +};
fuera del alcance del ticket

2022-03-01 18:21 UTC, maxxCeballos commented on routes/categories.js
> +);
fuera del alcance del ticket

2022-03-01 18:21 UTC, maxxCeballos commented on controllers/categories.js
> +      });
un 404 no es muy apropiado para el caso, los errores 4xx indican que hay un error por parte del cliente, en este caso, el cliente hace una request valida, el tema es que no hay contenido para mostrar, podes devolver un 200 devolviendo la lista vacia, o un 204 tambien puede ser viable.

2022-03-01 18:21 UTC, maxxCeballos commented on controllers/categories.js
> +    if (categories.length === 0 || !categories) {
por qué la doble validación?

2022-03-02 00:50 UTC, nathandelgado-dev commented on middlewares/categories.js
> +};
Si Bro el tema fue que parti de la branch de crear categoría por eso me refleja esos cambios también.

2022-03-02 00:53 UTC, nathandelgado-dev commented on controllers/categories.js
> +      });
Corregido!

2022-03-02 00:55 UTC, nathandelgado-dev commented on controllers/categories.js
> +    if (categories.length === 0 || !categories) {
Corregido!...Lo tenia ahi porque antes me comprobaba cuando no encontraba nada en la respuesta, pero si la base de datos no esta creada eso ya lo esta atrapando el catch. Quedo solo con el length.

2022-03-04 22:08 UTC, merged