Ot141 39 setup amazon s3 sdk
alkemyTech/OT141-SERVER pull request #29
Opened 2022-03-05 03:58 UTC by ema201217

- COMO usuario administrador
QUIERO subir imágenes en el sistema
PARA mejorar la comunicación

- Criterios de aceptación:
Se deberá vincular el servicio para manejo de archivos Amazon S3, a través de su SDK para Node.js. El mismo se utilizará posteriormente para campos de diferentes entidades, como la foto de perfil del usuario, logo de ONG, imágenes del blog y demás, por lo que debe crearse un servicio reutilizable para el manejo de archivos.

2022-03-09 12:10 UTC, maxxCeballos requested changes

2022-03-09 12:10 UTC, maxxCeballos commented on helpers/uploadAWS-S3.js
> +  if (!Body) throw new Error('The file is invalid');
Ema por el momento esta validación no la agreguemos, dejemos solo la funcion de subir el archivo. De todos modos no estaria validando bien, si mando un json 
{
    name: "ema",
    buff: Buffer.from([257, 257.5, -255, '1'])
}

pasa la validacion y no es una imagen que quiera guardar. Por otro lado, mas alla de esto, tratemos de enfocarnos en las responsabilidades, las validaciones hacerlas en otro lugar, asi podes reutilizar la funcion para subir cualquier tipo de archivo y las validaciones hacerlas en otro lugar, un middle por ejemplo.

2022-03-09 13:48 UTC, ema201217 commented on helpers/uploadAWS-S3.js
> +  if (!Body) throw new Error('The file is invalid');
Buffer no es cualquier contenido binario?,osea no solo imagen sino cualquier cosa. Lo único que detecta mandar correctente el contenido binario del archivo para que cuando se consuma la información de la nube no esté el archivo como dañado. Así es como lo probe. Esa parte no especifica solo imágenes sino que se mandé el Body correctamente.

2022-03-09 13:50 UTC, ema201217 commented on helpers/uploadAWS-S3.js
> +  if (!Body) throw new Error('The file is invalid');
Cómo quieras yo lo saco pedo después en cada caso que se utilicé se va a tener que hacer una validación en cada caso que se quiera utilizar la función. Avísame y lo saco..

2022-03-10 00:02 UTC, maxxCeballos approved these changes

2022-03-10 04:28 UTC, merged