Add Ticket completed with comments in english
alkemyTech/OT141-SERVER pull request #4
Opened 2022-02-22 01:21 UTC by ema201217

## Entity Activities - Branch [OT141-52-endpoint-creación-actividades](https://github.com/alkemyTech/OT141-SERVER/compare/feature/OT141-52-endpoint-creación-actividades)
-----------------------------------------------------------
### [Roadmap Jira - Actividades](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT141/boards/214/roadmap?selectedIssue=OT141-1)
-----------------------------------------------------------
### Homework assignment

- COMO usuario administrador
 QUIERO dar de alta Actividades
 PARA informarlas en el sistema

- Criterios de aceptación:
POST /activities - Deberá validar la existencia de los campos name y content enviados, para almacenar el registro en la tabla activities.

----------------------------------------------------------
## Info extra
#### [My Challenge](https://github.com/ema201217/Challenge-Backend-NodeJs)

2022-02-22 20:51 UTC, maxxCeballos requested changes

2022-02-22 20:51 UTC, maxxCeballos commented on .env.example
> -DB_PORT=3306
por qué se elimina?

2022-02-22 20:51 UTC, maxxCeballos commented on routes/users.js
>    res.send('respond with a resource');
Evitar cambios que no sean propios de la tarea

2022-02-22 20:51 UTC, maxxCeballos commented on routes/activities.js
> +
Evitaria poner el add (verbo) sobre la url, http esta orientado a recursos, por lo que especificar un post sobre activities (sustantivo) mas un nombre apropiado del controllador, se entiende la accion que se quiere realizar.

2022-02-22 20:51 UTC, maxxCeballos commented on routes/activities.js
> +
Quizas un nombre mas apropiado del folder seria middlewares

2022-02-22 23:29 UTC, ema201217 commented on controllers/activity.controller.js
> +    const errors = validationResult(req) // I get errors fetched from middleware made with express-validator
En esa parte del código, se obtiene los errores que existen por parte del cliente y luego abajo se evalúa ¿si no existen errores ? permite la ejecucion del codigo para poder crear la actividad  y si hay errores se manda como respuesta un código de error con un json

2022-02-22 23:31 UTC, ema201217 commented on routes/activities.js
> +
arreglando!!

2022-02-22 23:31 UTC, ema201217 commented on routes/users.js
>    res.send('respond with a resource');
Sin querer quizas indente el codigo

2022-02-22 23:31 UTC, ema201217 commented on .env.example
> -DB_PORT=3306
Lo elimine para que me tome el sistema en .env para variable de entorno

2022-02-22 23:32 UTC, ema201217 commented on routes/activities.js
> +
arreglando!!

2022-02-22 23:38 UTC, ema201217 commented on .env.example
> -DB_PORT=3306
reparado!!

2022-02-24 00:02 UTC, maxxCeballos approved these changes

2022-02-24 03:00 UTC, merged