activities test created for POST and PUT methods
alkemyTech/OT141-SERVER pull request #52
Opened 2022-03-12 23:17 UTC by fedapon

COMO desarrollador
QUIERO disponer de tests de los endpoints de /activities
PARA asegurar la integridad y funcionamiento del proyecto

Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración
![activities_test](https://user-images.githubusercontent.com/23043861/158038313-278e4758-513f-4b23-8151-4882a3c46e00.PNG)
.

2022-03-12 23:18 UTC, fedapon commented
Al realizar los test se detectó que el método PUT en \activities no actualiza los campos.

2022-03-18 18:01 UTC, maxxCeballos approved these changes

2022-03-18 18:06 UTC, maxxCeballos requested changes

2022-03-18 18:06 UTC, maxxCeballos commented on tests/endpoints/activities.test.js
> +      .expect("Content-Type", /json/);
Se podria agregar como validacion que los datos devueltos correspondan con los datos de la activity que estas creando.

2022-03-18 21:30 UTC, merged