OT141-74 | Endpoint create members
alkemyTech/OT141-SERVER pull request #57
Opened 2022-03-15 01:59 UTC by nathandelgado-dev

COMO usuario
QUIERO crear un miembro
PARA actualizar la información de la web.

Criterios de aceptación:
POST /members - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-03-15 02:27 UTC, maxxCeballos requested changes

2022-03-15 02:27 UTC, maxxCeballos commented on controllers/members.js
> +    const nameUpperCase = name.toUpperCase();
por que se pasa a upperCase?

2022-03-15 02:27 UTC, maxxCeballos commented on middlewares/members.js
> +  check('image', 'The value not is a string').isString(),
no se pide validacion sobre image.

2022-03-15 02:27 UTC, maxxCeballos commented on migrations/20220315001958-create-member.js
> +};
esto corresponde a ticket 72

2022-03-15 02:27 UTC, maxxCeballos commented on models/member.js
> +};
Esto corresponde a ticket 72

2022-03-15 22:36 UTC, nathandelgado-dev commented on controllers/members.js
> +    const nameUpperCase = name.toUpperCase();
Pensé que era unique y olvide quitar esa funcion.

2022-03-15 22:37 UTC, nathandelgado-dev commented on middlewares/members.js
> +  check('image', 'The value not is a string').isString(),
ok, debo dejar esa costumbre de hacer mas de lo que esta en la historia.

2022-03-15 22:38 UTC, nathandelgado-dev commented on models/member.js
> +};
Si es que esta branch la saque de la 72.

2022-03-15 22:38 UTC, nathandelgado-dev commented on migrations/20220315001958-create-member.js
> +};
Si es que esta branch la saque de la 72.

2022-03-16 20:18 UTC, maxxCeballos approved these changes

2022-03-17 22:36 UTC, merged