fix testimony put endpoint
alkemyTech/OT141-SERVER pull request #76
Opened 2022-03-21 23:31 UTC by facu142

Arreglos realizados:
- Se modificó la respuesta del endpoint de actualizacion de testimonio para que la misma  responda lo mismo que los endpoint de actualización de otras entidades (ej: activity)

2022-03-21 23:42 UTC, maxxCeballos requested changes

2022-03-21 23:42 UTC, maxxCeballos commented on controllers/testimony.js
> +        ...testimonyDb, name, image, content,
Facu pero aca no estarias devolviendo el testimonio antes de modificarlo?

2022-03-21 23:42 UTC, maxxCeballos commented on controllers/testimony.js
>      }
esto iria mejor antes del update, ya que no intentas hacer update si no hay un testimonio con ese id

2022-03-24 13:45 UTC, facu142 commented on controllers/testimony.js
>      }
corregido

2022-03-25 19:05 UTC, maxxCeballos commented
Este PR esta para borrarlo? Digo porque vi que hiciste el cambio en otro PR al final, si es asi, borremos este por favor!

2022-03-25 19:16 UTC, facu142 commented
> 

Si, Ema recien lo modificó, borro este PR

2022-03-25 19:16 UTC, closed without merging